#ifndef STATUS_H
#define STATUS_H

enum chime_status {
  OK,
  ERROR_USER_NOT_FOUND,
  ERROR_CONNECTION_REFUSED,
  ERROR_CONNECTION_DROPPED,
  ERROR_CONNECTION_LOST,
  ERROR_USERNAME_IN_USE,
  ERROR_INVALID_FILEPATH,
  ERROR_NOT_SENT,
  ERROR_FAILED_SYSCALL
};

#endif

